### ISSUE TITLE
Add export functionality

### ISSUE THREAD

**Issue by jlevers** [sunrisemovement/sunrise-strike-circles#22]
Direct request from Luis:

Want to pull data from the backend, and zap it to airtable, where we match it to the strike circles
* Status (ie. which week the circle is currently ‘on’)
* Cumulative number of pledges input
* Cumulative number of 1:1s input
* Last logged in (if easy to set up)
Finally, would love to zap all of the pledges data we’re getting to a new table in AirTable. This is less urgent, however.

**Comment by luismarchese** [comment]
hiii friends, this is our top priority once the program is fully functional!
