### ISSUE TITLE
Extend  (?) Sunrise's SSL to our domain

### ISSUE THREAD

**Issue by luismarchese** [sunrisemovement/sunrise-strike-circles#37]
Let me know if I put that right.

**Comment by jlevers** [comment]
I think that since we're running `strikecircle.sunrisemovement.org` on a different server than `sunrisemovement.org`, we'll have to create our own SSL certs...but that's totally doable. I'll figure this out.

**Comment by jlevers** [comment]
All set -- https://strikecircle.sunrisemovement.org/ now redirects all traffic to HTTPS.

**Comment by luismarchese** [comment]
AMAZING!! thank you!

Luis Marchese
Distributed Organizing | Sunrise Movement | he/they
